// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/urls": {
            "post": {
                "description": "Create a new url for monitoring.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Url"
                ],
                "summary": "Create a new url",
                "parameters": [
                    {
                        "description": "Create Url request",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateUrlRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Board successfully created",
                        "schema": {
                            "$ref": "#/definitions/urls.CreateUrlEnvelop"
                        }
                    },
                    "400": {
                        "description": "Empty body request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorEnvelope"
                        }
                    },
                    "402": {
                        "description": "Invalid request (e.g., missing parameters or validation error)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.UrlStatus": {
            "type": "integer",
            "enum": [
                10,
                20,
                25,
                30,
                40
            ],
            "x-enum-varnames": [
                "StatusHealthy",
                "StatusDegraded",
                "StatusRecovering",
                "StatusDown",
                "StatusNotified"
            ]
        },
        "dtos.CreateUrlRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "https://api.meuservico.com/health"
                },
                "contact_email": {
                    "type": "string",
                    "example": "meu_contato@email.com"
                },
                "interval_minutes": {
                    "type": "integer",
                    "example": 5
                },
                "next_check": {
                    "type": "string"
                },
                "retry_limit": {
                    "type": "integer",
                    "example": 3
                },
                "status": {
                    "$ref": "#/definitions/domain.UrlStatus"
                }
            }
        },
        "dtos.CreateUrlResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "urls.CreateUrlEnvelop": {
            "type": "object",
            "properties": {
                "url": {
                    "$ref": "#/definitions/dtos.CreateUrlResponse"
                }
            }
        },
        "utils.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
