// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Gustavo Cesar Santos",
            "email": "gustavocs789@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Monitor API health.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Monitor health check",
                "responses": {
                    "200": {
                        "description": "API is healthy",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_monitor_presentation_handlers.HealthCheckEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/GustavoCesarSantos_checkly-api_internal_shared_utils.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/urls": {
            "post": {
                "description": "Create a new url for monitoring.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Url"
                ],
                "summary": "Create a new url",
                "parameters": [
                    {
                        "description": "Create Url request",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GustavoCesarSantos_checkly-api_internal_modules_urls_presentation_dtos.CreateUrlRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Board successfully created",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_urls_presentation_handlers.CreateUrlEnvelop"
                        }
                    },
                    "400": {
                        "description": "Empty body request",
                        "schema": {
                            "$ref": "#/definitions/GustavoCesarSantos_checkly-api_internal_shared_utils.ErrorEnvelope"
                        }
                    },
                    "402": {
                        "description": "Invalid request (e.g., missing parameters or validation error)",
                        "schema": {
                            "$ref": "#/definitions/GustavoCesarSantos_checkly-api_internal_shared_utils.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/GustavoCesarSantos_checkly-api_internal_shared_utils.ErrorEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "GustavoCesarSantos_checkly-api_internal_modules_monitor_presentation_dtos.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "available"
                },
                "system_info": {
                    "$ref": "#/definitions/GustavoCesarSantos_checkly-api_internal_modules_monitor_presentation_dtos.SystemInfo"
                }
            }
        },
        "GustavoCesarSantos_checkly-api_internal_modules_monitor_presentation_dtos.SystemInfo": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string",
                    "example": "development"
                },
                "time": {
                    "type": "string",
                    "example": "2024-06-01T12:00:00Z"
                }
            }
        },
        "GustavoCesarSantos_checkly-api_internal_modules_urls_domain.UrlStatus": {
            "type": "integer",
            "enum": [
                10,
                20,
                25,
                30,
                40
            ],
            "x-enum-varnames": [
                "StatusHealthy",
                "StatusDegraded",
                "StatusRecovering",
                "StatusDown",
                "StatusNotified"
            ]
        },
        "GustavoCesarSantos_checkly-api_internal_modules_urls_presentation_dtos.CreateUrlRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "https://api.meuservico.com/health"
                },
                "contact_email": {
                    "type": "string",
                    "example": "meu_contato@email.com"
                },
                "interval_minutes": {
                    "type": "integer",
                    "example": 5
                },
                "next_check": {
                    "type": "string"
                },
                "retry_limit": {
                    "type": "integer",
                    "example": 3
                },
                "status": {
                    "$ref": "#/definitions/GustavoCesarSantos_checkly-api_internal_modules_urls_domain.UrlStatus"
                }
            }
        },
        "GustavoCesarSantos_checkly-api_internal_modules_urls_presentation_dtos.CreateUrlResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "GustavoCesarSantos_checkly-api_internal_shared_utils.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "internal_modules_monitor_presentation_handlers.HealthCheckEnvelope": {
            "type": "object",
            "properties": {
                "health_check": {
                    "$ref": "#/definitions/GustavoCesarSantos_checkly-api_internal_modules_monitor_presentation_dtos.HealthCheckResponse"
                }
            }
        },
        "internal_modules_urls_presentation_handlers.CreateUrlEnvelop": {
            "type": "object",
            "properties": {
                "url": {
                    "$ref": "#/definitions/GustavoCesarSantos_checkly-api_internal_modules_urls_presentation_dtos.CreateUrlResponse"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Checkly API",
	Description:      "API responsável por monitorar URLs e avaliar sua disponibilidade.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
